# 该容器使用 4*** 端口

name: my-gitlab
version: '1.0'

services:
  gitlab:
    image: gitlab/gitlab-ce:16.11.10-ce.0 # 镜像名称以及版本
    restart: unless-stopped
    container_name: gitlab-service # 容器名称
    hostname: 'gitlab.fallzhang.top'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.fallzhang.top:4080'
        gitlab_rails['gitlab_shell_ssh_port'] = 4022
    # 指定挂载目录
    volumes:
      - "./config:/etc/gitlab"
      - "./logs:/var/log/gitlab"
      - "./data:/var/opt/gitlab"
    ports:
      - "4022:22"
      - "4080:4080"
      - "4443:443"
    shm_size: '256m'

