# 该容器使用 4*** 端口
version: '3.6'
name: gitlab-gitlab

services:
  gitlab:
    image: gitlab/gitlab-ce:16.11.10-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.fallzhang.top'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.fallzhang.top:4080'
        gitlab_rails['gitlab_shell_ssh_port'] = 4022
    ports:
      - '4080:4080'
      - '443:443'
      - '4022:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
