services:

  nginx-proxy:
    image: nginx:1.26.1-alpine-otel
    container_name: nginx-service # 容器名称
    restart: unless-stopped
    volumes:
    # - ./templates:/etc/nginx/templates
    - ./nginx/log:/var/log/nginx
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./html:/usr/share/nginx/html:ro
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=fallzhang.com
    - NGINX_PORT=80

  # nginx:
  #   image: nginx:1.26.1-alpine-otel
  #   restart: always
  #   container_name: nginx-nocode
  #   ports:
  #     - 7280:80
  #     - 7243:443
  #   volumes:
  #     - ./nginx/html:/usr/share/nginx/html
  #     - ./nginx/log:/var/log/nginx
  #     - ./nginx/conf:/etc/nginx/conf.d
